version: '3.4'
services:
  kanboard:
    image: kanboard/kanboard:latest
    depends_on:
      - db
    ports:
      - "8084:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kanboard:kanboard-secret@db/kanboard
    networks:
      - kanboard-db
      - traefik
    labels:
      - "traefik.http.routers.kanboard.rule=Host(`task.dev03.zahite.net`)"
      - "traefik.http.routers.kanboard.tls=true"
      - "traefik.docker.network=traefik_kanboard"      
        
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: kanboard-secret
    volumes:
    - kanboard-db:/var/lib/mysql
    networks:
      - kanboard-db
  

volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  kanboard-db:

networks:
  kanboard-db:
    driver: overlay
  traefik:
    external:
      name: traefik_kanboard
      
      
