version: '2'
services:
kanboard:
  image: kanboard/kanboard:latest
  ports:
    - "8083:80"
  volumes:
    - kanboard_data:/var/www/app/data
    - kanboard_plugins:/var/www/app/plugins
    - kanboard_ssl:/etc/nginx/ssl
  environment:
    DATABASE_URL: mysql://kanboard:kanboard-secret@db/kanboard
  networks:
    - kanboard-db
    - traefik
      
        
db:
  image: mariadb:latest
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: kanboard
    MYSQL_USER: kanboard
    MYSQL_PASSWORD: kanboard-secret
  volumes:
  - kanboard-db:/var/lib/mysql
  networks:
    - kanboard-db


volumes:
kanboard_data:
kanboard_plugins:
kanboard_ssl:
kanboard-db:

networks:
  kanboard-db:
    driver: overlay
