version: "3.7"

  
services:

  traefik:
      image: traefik
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./config/traefik.toml:/etc/traefik/traefik.toml
        - ./certs/:/certs/
#      command: --api.insecure=true --providers.docker 
      ports:
        - 80:80
        - 8080:8080
        - 443:443
      networks:
        - readme
        - uptime-kuma
        - miniflux



networks:
  readme:
    attachable: true
    driver: overlay

  uptime-kuma:
    attachable: true
    driver: overlay

  miniflux:
    attachable: true
    driver: overlay




