version: "3.7"

  
services:

  traefik:
      image: traefik
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./config/traefik.toml:/etc/traefik/traefik.toml
#      command: --api.insecure=true --providers.docker 
      ports:
        - 80:80
        - 8080:8080
        - 443:443
      networks:
        - readme
        - uptime-kuma
        - miniflux
        - kanboard
        - node-red
        - jenkins
        - linkace

networks:
  readme:
    attachable: true
    driver: overlay

  uptime-kuma:
    attachable: true
    driver: overlay

  miniflux:
    attachable: true
    driver: overlay

  kanboard:
    attachable: true
    driver: overlay

  node-red:
    attachable: true
    driver: overlay

  linkace:
    attachable: true
    driver: overlay
  
  jenkins:
    attachable: true
    driver: overlay


