[api]	
  insecure = true
  dashboard = true

[providers.docker]

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "satiku@gmail.com
  storage = acme.json

  [certificatesResolvers.myresolver.acme.tlsChallenge]
    entryPoint = "web"


#[[tls.certificates]]
#  certFile = "/certs/zahite.crt"
#  keyFile = "/certs/zahite.key"
#
#
