version: '3.4'
services:
  fbc-nginx:
    image: nginx
    user: 0:0 
    volumes:
     - ./content:/www/data:ro
     - ./fbc-nginx.conf:/etc/nginx/conf.d/fbc-nginx.conf:ro
    ports:
     - "8087:80"
    labels:
      - "traefik.http.routers.fbc-nginx.rule=Host(`fbc.dev03.zahite.net`)"
      - "traefik.http.routers.fbc-nginx.tls=true"
      - "traefik.http.routers.fbc-nginx.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik_fbc-nginx"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_fbc-nginx
