### EXAMPLE DOCKER COMPOSE ###
version: "3.7"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - audiobookshelf-audiobooks:/audiobooks
      - audiobookshelf-metadata:/metadata
      - audiobookshelf-config:/config
    restart: unless-stopped
    networks:
      - traefik


volume: 
  audiobookshelf-audibooks:
  audiobookshelf-metadata:
  audiobookshelf-config:

networks:
  traefik:
    external:
      name: traefik_kanboard


