version: "3.7"

  
services:

  readme:
      image: nginx
      volumes:
        - ./content:/usr/share/nginx/html:ro
      ports:
        - 8080:80
      networks:
        - frontend




networks:
    frontend:
      external:
        name: frontend-readme
        
