version: "3.7"

  
services:

  readme:
      image: nginx
      volumes:
        - ./content:/usr/share/nginx/html:ro
      ports:
        - 8081:80
      labels:
        - "traefik.http.routers.readme.rule=Host(`dev03.zahite.net`)"
        - "traefik.http.routers.readme.tls=true"
        - "traefik.docker.network=traefik-readme"
      networks:
        - traefik




networks:
  traefik:
    external:
      name: traefik-readme



